version: '2.1'
services:
  web:
    image: smarthome/web:0.0.1-SNAPSHOT
    environment:
      PROFILE: "dev"
    ports:
      - "8080:8080"
    networks:
      backend:
        aliases:
          - "web"

  sensor:
    image: smarthome/sensor:0.0.1-SNAPSHOT
    environment:
      PROFILE: "dev"
    ports:
      - "8081:8081"
    networks:
      backend:
        aliases:
          - "sensor"

networks:
  backend:
    driver: bridge